#! /bin/bash

DOCKER_NAME="coles"
CONTAINER_NAME="bazarova-coles4"
SRC="macro_micro_coles"
DOCKER_USER_ID=1035 # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=1035
CONTAINER_PORT=8973 # used in launch_container file
