#! /bin/bash

DOCKER_NAME="macro-micro-coles" # username in container
CONTAINER_NAME=$USER"-mmcoles" # name of container
SRC="transactions_gen_models" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=$(id -u) 
DOCKER_GROUP_ID=$(id -g)
