#! /bin/bash

DOCKER_NAME="macro-micro-coles"
CONTAINER_NAME="belousov-mmcoles"
SRC="macro_micro_coles"
DOCKER_USER_ID=1023 # to get these values type "id" in shell termilal
DOCKER_GROUP_ID=1023
CONTAINER_PORT=8893 # used in launch_container file