#! /bin/bash

DOCKER_NAME="macro-micro-coles" # username in container
CONTAINER_NAME="ilykuleshov-mmcoles" # name of container
SRC="macro_micro_coles" # source directory (supposedly, this repo's path is /home/${USER}/${SRC})

# to get these values type "id" in shell termilal
DOCKER_USER_ID=1015 
DOCKER_GROUP_ID=1015

PORT=8123
# rename this file to "credentials" when done