_target_: src.modules.CustomCoLES
optimizer_partial:
  _partial_: True
  _target_: torch.optim.Adam
  lr: 0.001
  weight_decay: 0
lr_scheduler_partial:
  _partial_: True
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  factor: 0.9025
  patience: 2
  